/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2S_1.h"
#include "I2S_1_PVT.h"
#include "Speaker_aliases.h"
#include "Speaker.h"
#include "VDAC8.h"
#include "USBFS.h"
#include "USBFS_audio.h"
#include "USBFS_cdc.h"
#include "USBFS_hid.h"
#include "USBFS_midi.h"
#include "USBFS_pvt.h"
#include "USBFS_cydmac.h"
#include "USBFS_msc.h"
#include "VdacDma_dma.h"
#include "SampleClk.h"
#include "DmaDone.h"
#include "clock.h"
#include "TxDMA_dma.h"
#include "MCLK_aliases.h"
#include "MCLK.h"
#include "USBFS_ep6_dma.h"
#include "USBFS_ep1_dma.h"
#include "USBFS_Dm_aliases.h"
#include "USBFS_Dm.h"
#include "USBFS_Dp_aliases.h"
#include "USBFS_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

