/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "SleepTimer.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "MIDI_PWR_aliases.h"
#include "MIDI_PWR.h"
#include "LED_OutB_aliases.h"
#include "LED_OutB.h"
#include "LED_InB_aliases.h"
#include "LED_InB.h"
#include "LED_OutA_aliases.h"
#include "LED_OutA.h"
#include "LED_InA_aliases.h"
#include "LED_InA.h"
#include "MIDI1_UART.h"
#include "MIDI2_UART.h"
#include "Clock_1.h"
#include "USB.h"
#include "USB_audio.h"
#include "USB_cdc.h"
#include "USB_hid.h"
#include "USB_midi.h"
#include "USB_pvt.h"
#include "USB_cydmac.h"
#include "USB_msc.h"
#include "Sleep_isr.h"
#include "USB_Dm_aliases.h"
#include "USB_Dm.h"
#include "USB_Dp_aliases.h"
#include "USB_Dp.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

